import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';
import InstagramIcon from '../components/Icon';
import FacebookIcon from '../components/FacebookIcon';
import LinkedInIcon from '../components/LinkedInIcon';

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero
        heading='About me!'
        message='Hi, my name is Saad El-Amri, and I am a passionate computer science graduate with a particular interest in coding and app development I have experience in iOS development, Android development, and database management, and I enjoy taking on new challenges and learning something new with each project.'
      />

      <Slider slides={SliderData} />
      <div className='flex justify-center mt-8 space-x-8 mb-4'>
        <InstagramIcon />
        <FacebookIcon />
        <LinkedInIcon />
      </div>
    </div>
  );
}
